### PR TITLE
Adding support for compiling against pppd-2.5.0 (current master)

### PR DESCRIPTION
**Pull request by enaess**
Sorry, had a force update of the branch a minute later than you merged it into main. 

This one include the actual nm-l2tp-ppp-status.h and fixes to Makefile.am. Compiles against both ppp 2.4.9 and current master (2.5.0).

### CODE REVIEW

**Comment by dkosovic** [comment]
No worries.

I just read the code and thought it looked okay, I didn't test. Will test and merge when I get home

**Comment by enaess** [comment]
Cool! I don't have a good l2tp setup, but I did validate the change against the sstp variant.

Also, pppd 2.5.0 has cool features like peap-mschapv2. Look to salsa / debian for configure argument to set it up. Project switched to using autotools now

**Comment by dkosovic** [comment]
Looking forward to the new pppd-2.5.0.

I built the current master pppd on Fedora 37.

I just tried building building your pull request, but get the following error message:
```sh
 CC       src/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo
In file included from src/nm-l2tp-pppd-plugin.c:20:
src/nm-l2tp-pppd-compat.h:50:11: fatal error: pppd/chap-new.h: No such file or directory
   50 |  #include <pppd/chap-new.h>
      |           ^~~~~~~~~~~~~~~~~
compilation terminated.
```

In the current master pppd, the `pppd/chap.h` header has:
```C
/*
 * chap-new.c - New CHAP implementation.
```

**Comment by enaess** [comment]
Did you rerun autogen.sh?

**Comment by dkosovic** [comment]
I did, but looking at my history it was before I did `sudo rpm -e ppp ppp-devel` to remove the older version.

All good now, thanks. I'll merge it.

**Comment by enaess** [comment]
It would be good if you run some additional smoke test on pppd 2.5.0. if there is anything needs changing, now would be the time.

**Comment by enaess** [comment]
That would be awesome. Thanks for merging

**Pull request merged**
